{
 "title": "Database Backup Monitoring",
 "tags": [ "backwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(backup_overdue)" }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(backup_overdue) - (sum(backup_failure_total) + sum(backup_overdue))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(backup_failure_total[1h]))"
    }
   ]
  },
  {
   "title": "Overdue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "sum(backup_overdue)" }
   ]
  },
  {
   "title": "Application Backup Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "backup_overdue" }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "backup_size_bytes" }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "backup_duration_seconds" }
   ]
  }
 ]
}